/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#571295',
        'primary-container': '#7033ae',
        'on-primary': '#ffffff',
        'on-primary-container': '#ddbbff',
        'surface': '#faf9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#faf9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e3e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#4c4452',
        'outline': '#7d7483',
        'outline-variant': '#cec3d4',
        'tertiary': '#80001e',
        'tertiary-container': '#a90c2d',
        'on-tertiary': '#ffffff',
        'secondary': '#724c9f',
        'secondary-container': '#cda4fe',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'pastel-blue': '#E0F2FE',
        'pastel-green': '#F0FDF4',
        'pastel-pink': '#FDF2F8',
        'pastel-yellow': '#FEFCE8',
        'pastel-purple': '#F5F3FF',
        'pastel-orange': '#FFF7ED',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '3rem',
        '4xl': '3.5rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0 10px 30px -5px rgba(87, 18, 149, 0.08)',
        playful: '0 20px 40px -12px rgba(87, 18, 149, 0.12)',
      },
    },
  },
  plugins: [],
}
